### ISSUE TITLE
Chrome 119 Extension Install

### ISSUE THREAD

**Issue by LizzyEll** [AshtonDavies/bookmarklet-executor#3]
Was this patched?
![image](https://github.com/AshtonDavies/bookmarklet-executor/assets/92237193/7d2bc8ca-7f32-48c5-ba3c-cd2928f1b2a3)

**Comment by AshtonDavies** [comment]
It was never really "unpatched" in the first place. It is meant for installing extensions from the Chrome Web Store if it is blocked.
